#pragma once


namespace BULLET
{
	enum DIR
	{
		LEFT, RIGHT, UP, DOWN, END
	};
}

namespace OBJID
{
	enum ID
	{
		PLAYER, BULLET, MONSTER, MONSTERBULLET, MONSTERBULLET2, MONSTERBULLET3, MONSTERBULLET4, MONSTERBULLET5, BOSS, BOSSBULLET, BOMB, POWER, IBOMB, END
	};
}

enum SCENEID
{
	SCENE_LOGO, SCENE_STAGE, SCENE_END
};

enum RENDERID { RENDER_BACK, RENDER_OBJ, RENDER_EFFECT, RENDER_UI, RENDER_END };
